import { PT_Sans as PTSans, PT_Sans_Narrow as PtSansNarrow } from 'next/font/google';
import { RadixProvider } from '@/ui/theme';
import type { Metadata } from 'next';

// TODO: install local fonts
const ptSans = PTSans({
  variable: '--font-pt-sans',
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700'],
});

const ptSansNarrow = PtSansNarrow({
  variable: '--font-pt-sans-narrow',
  subsets: ['cyrillic', 'latin'],
  weight: ['700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="ru">
    <body className={`${ptSansNarrow.variable} ${ptSans.variable}`}>
      <RadixProvider>{children}</RadixProvider>
    </body>
  </html>
);

export default RootLayout;
